application: visual-office
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: ../public/index.html
  upload: ../public/index.html

- url: /(.*\.(css|js|png))
  static_files: ../public/\1
  upload: ../public/(.*\.(css|js|png))

- url: /.*
  script: visualoffice.app
